// <auto-generated />
using System;
using LancamentosOnline.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LancamentosOnline.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710192235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Andar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("TorreId")
                        .HasColumnType("integer")
                        .HasColumnName("torre_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_andares");

                    b.HasIndex("TorreId")
                        .HasDatabaseName("i_x_andares_torre_id");

                    b.ToTable("andares");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Bairro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("cidade_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_bairros");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("i_x_bairros_cidade_id");

                    b.ToTable("bairros");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_cidades");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("i_x_cidades_estado_id");

                    b.ToTable("cidades");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text")
                        .HasColumnName("estado_civil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_clientes");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Construtora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcessoDomus")
                        .HasColumnType("boolean")
                        .HasColumnName("acesso_domus");

                    b.Property<int?>("AnoFundacao")
                        .HasColumnType("integer")
                        .HasColumnName("ano_fundacao");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("MesFundacao")
                        .HasColumnType("integer")
                        .HasColumnName("mes_fundacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeAbreviado")
                        .HasColumnType("text")
                        .HasColumnName("nome_abreviado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorMensal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_mensal");

                    b.HasKey("Id")
                        .HasName("p_k_construtoras");

                    b.ToTable("construtoras");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Empreendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("GerouUnidades")
                        .HasColumnType("boolean")
                        .HasColumnName("gerou_unidades");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("Logomarca")
                        .HasColumnType("text")
                        .HasColumnName("logomarca");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PrevisaoEntrega")
                        .HasColumnType("text")
                        .HasColumnName("previsao_entrega");

                    b.Property<int>("QtdeQuadra")
                        .HasColumnType("integer")
                        .HasColumnName("qtde_quadra");

                    b.Property<int>("QtdeTorre")
                        .HasColumnType("integer")
                        .HasColumnName("qtde_torre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_final");

                    b.Property<decimal?>("ValorInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_inicial");

                    b.HasKey("Id")
                        .HasName("p_k_empreendimentos");

                    b.HasIndex("ConstrutoraId")
                        .HasDatabaseName("i_x_empreendimentos_construtora_id");

                    b.ToTable("empreendimentos");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BairroId")
                        .HasColumnType("integer")
                        .HasColumnName("bairro_id");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<int?>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_enderecos");

                    b.ToTable("enderecos");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_estados");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Garagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("empreendimento_id");

                    b.Property<string>("FormatoVaga")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato_vaga");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("PavimentoGaragemId")
                        .HasColumnType("integer")
                        .HasColumnName("pavimento_garagem_id");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<int?>("TorreId")
                        .HasColumnType("integer")
                        .HasColumnName("torre_id");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("unidade_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_garagens");

                    b.ToTable("garagens");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("empreendimento_id");

                    b.Property<decimal>("EntradaProposta")
                        .HasColumnType("numeric")
                        .HasColumnName("entrada_proposta");

                    b.Property<int?>("OfertaId")
                        .HasColumnType("integer")
                        .HasColumnName("oferta_id");

                    b.Property<int?>("QuantidadeParcela")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcela");

                    b.Property<decimal?>("SaldoRemanescente")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_remanescente");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("unidade_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorBens")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_bens");

                    b.Property<decimal?>("ValorParcela")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_parcela");

                    b.Property<decimal>("ValorProposta")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_proposta");

                    b.HasKey("Id")
                        .HasName("p_k_propostas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("i_x_propostas_cliente_id");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("i_x_propostas_unidade_id");

                    b.ToTable("propostas");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.PropostaBalao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("proposta_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("p_k_propostas_baloes");

                    b.HasIndex("PropostaId")
                        .HasDatabaseName("i_x_propostas_baloes_proposta_id");

                    b.ToTable("propostas_baloes");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.PropostaVaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("GaragemId")
                        .HasColumnType("integer")
                        .HasColumnName("garagem_id");

                    b.Property<int>("PropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("proposta_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_propostas_vagas");

                    b.HasIndex("GaragemId")
                        .HasDatabaseName("i_x_propostas_vagas_garagem_id");

                    b.HasIndex("PropostaId")
                        .HasDatabaseName("i_x_propostas_vagas_proposta_id");

                    b.ToTable("propostas_vagas");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Quadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("empreendimento_id");

                    b.Property<bool>("GerouUnidades")
                        .HasColumnType("boolean")
                        .HasColumnName("gerou_unidades");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Nomenclatura")
                        .HasColumnType("text")
                        .HasColumnName("nomenclatura");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("PrevisaoEntrega")
                        .HasColumnType("text")
                        .HasColumnName("previsao_entrega");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalUnidades")
                        .HasColumnType("integer")
                        .HasColumnName("total_unidades");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_quadras");

                    b.HasIndex("EmpreendimentoId")
                        .HasDatabaseName("i_x_quadras_empreendimento_id");

                    b.ToTable("quadras");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.TabelaVendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("empreendimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("QtdeParcelasEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("qtde_parcelas_entrada");

                    b.Property<int?>("QuadraId")
                        .HasColumnType("integer")
                        .HasColumnName("quadra_id");

                    b.Property<int>("TipoTabelaId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_tabela_id");

                    b.Property<int?>("TorreId")
                        .HasColumnType("integer")
                        .HasColumnName("torre_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorVagaExtra")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_vaga_extra");

                    b.HasKey("Id")
                        .HasName("p_k_tabela_vendas");

                    b.ToTable("tabela_vendas");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.TabelaVendasBaloes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataBalao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_balao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("PercentualBalao")
                        .HasColumnType("numeric")
                        .HasColumnName("percentual_balao");

                    b.Property<int>("TabelaVendasId")
                        .HasColumnType("integer")
                        .HasColumnName("tabela_vendas_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tabela_vendas_baloes");

                    b.HasIndex("TabelaVendasId")
                        .HasDatabaseName("i_x_tabela_vendas_baloes_tabela_vendas_id");

                    b.ToTable("tabela_vendas_baloes");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Torre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("empreendimento_id");

                    b.Property<string>("Etapa")
                        .HasColumnType("text")
                        .HasColumnName("etapa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("PrevisaoEntrega")
                        .HasColumnType("text")
                        .HasColumnName("previsao_entrega");

                    b.Property<int?>("PrevisaoEntregaAno")
                        .HasColumnType("integer")
                        .HasColumnName("previsao_entrega_ano");

                    b.Property<int?>("PrevisaoEntregaMes")
                        .HasColumnType("integer")
                        .HasColumnName("previsao_entrega_mes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_torres");

                    b.HasIndex("EmpreendimentoId")
                        .HasDatabaseName("i_x_torres_empreendimento_id");

                    b.ToTable("torres");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AndarId")
                        .HasColumnType("integer")
                        .HasColumnName("andar_id");

                    b.Property<int>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("empreendimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("PlantaId")
                        .HasColumnType("integer")
                        .HasColumnName("planta_id");

                    b.Property<int?>("QuadraId")
                        .HasColumnType("integer")
                        .HasColumnName("quadra_id");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TorreId")
                        .HasColumnType("integer")
                        .HasColumnName("torre_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_unidades");

                    b.HasIndex("AndarId")
                        .HasDatabaseName("i_x_unidades_andar_id");

                    b.HasIndex("QuadraId")
                        .HasDatabaseName("i_x_unidades_quadra_id");

                    b.HasIndex("TorreId")
                        .HasDatabaseName("i_x_unidades_torre_id");

                    b.ToTable("unidades");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("celular");

                    b.Property<int?>("ConstrutoraId")
                        .HasColumnType("integer")
                        .HasColumnName("construtora_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("text")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PerfilProfissional")
                        .HasColumnType("text")
                        .HasColumnName("perfil_profissional");

                    b.Property<string>("TelefoneFixo")
                        .HasColumnType("text")
                        .HasColumnName("telefone_fixo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("ConstrutoraId")
                        .HasDatabaseName("i_x_users_construtora_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Andar", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Torre", "Torre")
                        .WithMany("Andares")
                        .HasForeignKey("TorreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_andares__torres_torre_id");

                    b.Navigation("Torre");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_bairros__cidades_cidade_id");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cidades__estados_estado_id");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Empreendimento", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Construtora", "Construtora")
                        .WithMany("Empreendimentos")
                        .HasForeignKey("ConstrutoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_empreendimentos_construtoras_construtora_id");

                    b.Navigation("Construtora");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Proposta", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_propostas_clientes_cliente_id");

                    b.HasOne("LancamentosOnline.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_propostas__unidades_unidade_id");

                    b.Navigation("Cliente");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.PropostaBalao", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Proposta", "Proposta")
                        .WithMany("Baloes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_propostas_baloes_propostas_proposta_id");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.PropostaVaga", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Garagem", "Garagem")
                        .WithMany()
                        .HasForeignKey("GaragemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_propostas_vagas_garagens_garagem_id");

                    b.HasOne("LancamentosOnline.Domain.Entities.Proposta", "Proposta")
                        .WithMany("Vagas")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_propostas_vagas_propostas_proposta_id");

                    b.Navigation("Garagem");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Quadra", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Empreendimento", "Empreendimento")
                        .WithMany("Quadras")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_quadras_empreendimentos_empreendimento_id");

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.TabelaVendasBaloes", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.TabelaVendas", "TabelaVendas")
                        .WithMany("Baloes")
                        .HasForeignKey("TabelaVendasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tabela_vendas_baloes_tabela_vendas_tabela_vendas_id");

                    b.Navigation("TabelaVendas");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Torre", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Empreendimento", "Empreendimento")
                        .WithMany("Torres")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_torres_empreendimentos_empreendimento_id");

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Unidade", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Andar", "Andar")
                        .WithMany()
                        .HasForeignKey("AndarId")
                        .HasConstraintName("f_k_unidades_andares_andar_id");

                    b.HasOne("LancamentosOnline.Domain.Entities.Quadra", "Quadra")
                        .WithMany("Unidades")
                        .HasForeignKey("QuadraId")
                        .HasConstraintName("f_k_unidades_quadras_quadra_id");

                    b.HasOne("LancamentosOnline.Domain.Entities.Torre", "Torre")
                        .WithMany("Unidades")
                        .HasForeignKey("TorreId")
                        .HasConstraintName("f_k_unidades_torres_torre_id");

                    b.Navigation("Andar");

                    b.Navigation("Quadra");

                    b.Navigation("Torre");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.User", b =>
                {
                    b.HasOne("LancamentosOnline.Domain.Entities.Construtora", "Construtora")
                        .WithMany("Users")
                        .HasForeignKey("ConstrutoraId")
                        .HasConstraintName("f_k_users_construtoras_construtora_id");

                    b.Navigation("Construtora");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Construtora", b =>
                {
                    b.Navigation("Empreendimentos");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Empreendimento", b =>
                {
                    b.Navigation("Quadras");

                    b.Navigation("Torres");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Proposta", b =>
                {
                    b.Navigation("Baloes");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Quadra", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.TabelaVendas", b =>
                {
                    b.Navigation("Baloes");
                });

            modelBuilder.Entity("LancamentosOnline.Domain.Entities.Torre", b =>
                {
                    b.Navigation("Andares");

                    b.Navigation("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
