using Microsoft.EntityFrameworkCore;
using Novuu.Domain.Entities;
using Bogus;
using System;
using System.Linq;
using System.Collections.Generic;

namespace Novuu.Infrastructure.Data;

public static class DbInitializer
{
    public static void Seed(ApplicationDbContext context)
    {
        try
        {
            context.Database.Migrate();
        }
        catch { }

        try
        {
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS empreendimentos_subtipos (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    tipo VARCHAR(255) NOT NULL DEFAULT 'Vertical',
                    created_at TIMESTAMP WITH TIME ZONE,
                    updated_at TIMESTAMP WITH TIME ZONE,
                    deleted_at TIMESTAMP WITH TIME ZONE
                );
                CREATE TABLE IF NOT EXISTS empreendimentos_variacoes (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    subtipo_id INT REFERENCES empreendimentos_subtipos(id) ON DELETE CASCADE,
                    nome VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE,
                    updated_at TIMESTAMP WITH TIME ZONE,
                    deleted_at TIMESTAMP WITH TIME ZONE
                );
                ALTER TABLE empreendimentos ADD COLUMN IF NOT EXISTS subtipo_id INT;
                ALTER TABLE empreendimentos ADD COLUMN IF NOT EXISTS variacao_id INT;
                ALTER TABLE empreendimentos ADD COLUMN IF NOT EXISTS endereco_id INT;
            ");
        }
        catch { }

        // Seed Construtoras, Estados, Cidades, Bairros e Endereços from MySQL dumps
        SeedConstrutorasFromDump(context);
        SeedEstadosFromDump(context);
        SeedCidadesFromDump(context);
        SeedBairrosFromDump(context);
        SeedEnderecosFromDump(context);
        SeedEmpreendimentosEnderecosFromDump(context);

        // 1. Seed Estado
        if (!context.Estados.Any())
        {
            var mt = new Estado { Uf = "MT", Nome = "Mato Grosso" };
            context.Estados.Add(mt);
            context.SaveChanges();
        }
        var estadoMt = context.Estados.First();

        // 2. Seed Cidade
        if (!context.Cidades.Any())
        {
            var cuiaba = new Cidade { EstadoId = estadoMt.Id, Nome = "CuiabÃ¡" };
            var vg = new Cidade { EstadoId = estadoMt.Id, Nome = "VÃ¡rzea Grande" };
            var rondonopolis = new Cidade { EstadoId = estadoMt.Id, Nome = "RondonÃ³polis" };
            var sinop = new Cidade { EstadoId = estadoMt.Id, Nome = "Sinop" };
            context.Cidades.AddRange(cuiaba, vg, rondonopolis, sinop);
            context.SaveChanges();
        }
        var cidades = context.Cidades.ToList();

        // 3. Seed Bairros
        if (!context.Bairros.Any())
        {
            var bairros = new List<Bairro>();
            var nomesBairrosCuiaba = new[] { "Centro-Sul", "Bosque da SaÃºde", "Jardim AclimaÃ§Ã£o", "Jardim das AmÃ©ricas", "Goiabeiras", "Quilombo", "Santa Rosa", "Popular", "Alvorada", "Boa EsperanÃ§a", "Jardim ItÃ¡lia", "Morada do Ouro", "CoxipÃ³" };
            var cuiaba = cidades.First(c => c.Nome == "CuiabÃ¡");
            foreach (var nb in nomesBairrosCuiaba) bairros.Add(new Bairro { CidadeId = cuiaba.Id, Nome = nb });
            
            var nomesBairrosVG = new[] { "Centro", "Jardim Aeroporto", "Cristo Rei", "Jardim GlÃ³ria", "Nova VÃ¡rzea Grande", "Mapim" };
            var vg = cidades.First(c => c.Nome == "VÃ¡rzea Grande");
            foreach (var nb in nomesBairrosVG) bairros.Add(new Bairro { CidadeId = vg.Id, Nome = nb });

            context.Bairros.AddRange(bairros);
            context.SaveChanges();
        }
        var bairrosDb = context.Bairros.ToList();

        // 4. Seed Construtoras
        if (!context.Construtoras.Any())
        {
            var construtoras = new List<Construtora>
            {
                new Construtora { Nome = "Plaenge Empreendimentos", NomeAbreviado = "Plaenge", Cnpj = "00.000.000/0001-00", AcessoDomus = true },
                new Construtora { Nome = "Ginco Urbanismo", NomeAbreviado = "Ginco", Cnpj = "11.111.111/0001-11", AcessoDomus = false },
                new Construtora { Nome = "MRV Engenharia", NomeAbreviado = "MRV", Cnpj = "22.222.222/0001-22", AcessoDomus = false },
                new Construtora { Nome = "SÃ£o Benedito", NomeAbreviado = "SÃ£o Benedito", Cnpj = "33.333.333/0001-33", AcessoDomus = false },
                new Construtora { Nome = "Vanguard Home", NomeAbreviado = "Vanguard", Cnpj = "44.444.444/0001-44", AcessoDomus = true },
                new Construtora { Nome = "Cyrela", NomeAbreviado = "Cyrela", Cnpj = "55.555.555/0001-55", AcessoDomus = false },
                new Construtora { Nome = "Gafisa", NomeAbreviado = "Gafisa", Cnpj = "66.666.666/0001-66", AcessoDomus = false },
                new Construtora { Nome = "Tenda", NomeAbreviado = "Tenda", Cnpj = "77.777.777/0001-77", AcessoDomus = false },
                new Construtora { Nome = "Direcional", NomeAbreviado = "Direcional", Cnpj = "88.888.888/0001-88", AcessoDomus = false },
                new Construtora { Nome = "Even", NomeAbreviado = "Even", Cnpj = "99.999.999/0001-99", AcessoDomus = false },
                new Construtora { Nome = "Gerencial Construtora", NomeAbreviado = "Gerencial", Cnpj = "12.345.678/0001-10", AcessoDomus = false }
            };
            context.Construtoras.AddRange(construtoras);
            context.SaveChanges();
        }
        var construtorasDb = context.Construtoras.ToList();

        // 4.5. Seed Subtipos and Variacoes
        if (!context.Subtipos.Any())
        {
            var subtipos = new List<EmpreendimentoSubtipo>
            {
                new EmpreendimentoSubtipo { Id = 1, Nome = "Apartamento", Tipo = "Vertical" },
                new EmpreendimentoSubtipo { Id = 2, Nome = "Sala Comercial", Tipo = "Vertical" },
                new EmpreendimentoSubtipo { Id = 3, Nome = "Condomínio Fechado", Tipo = "Horizontal" },
                new EmpreendimentoSubtipo { Id = 4, Nome = "Residencial", Tipo = "Horizontal" },
                new EmpreendimentoSubtipo { Id = 5, Nome = "Comercial", Tipo = "Horizontal" }
            };
            context.Subtipos.AddRange(subtipos);
            context.SaveChanges();
        }
        var subtiposDb = context.Subtipos.ToList();

        if (!context.Variacoes.Any())
        {
            var variacoes = new List<EmpreendimentoVariacao>
            {
                new EmpreendimentoVariacao { Id = 1, SubtipoId = 1, Nome = "Studio" },
                new EmpreendimentoVariacao { Id = 2, SubtipoId = 1, Nome = "Loft" },
                new EmpreendimentoVariacao { Id = 3, SubtipoId = 1, Nome = "Padrão" },
                new EmpreendimentoVariacao { Id = 4, SubtipoId = 2, Nome = "Padrão" },
                new EmpreendimentoVariacao { Id = 5, SubtipoId = 2, Nome = "Coworking" },
                new EmpreendimentoVariacao { Id = 6, SubtipoId = 3, Nome = "Lote" },
                new EmpreendimentoVariacao { Id = 7, SubtipoId = 3, Nome = "Casa" },
                new EmpreendimentoVariacao { Id = 8, SubtipoId = 4, Nome = "Casa Térrea" },
                new EmpreendimentoVariacao { Id = 9, SubtipoId = 4, Nome = "Sobrado" },
                new EmpreendimentoVariacao { Id = 10, SubtipoId = 4, Nome = "Lote" },
                new EmpreendimentoVariacao { Id = 11, SubtipoId = 5, Nome = "Lote" }
            };
            context.Variacoes.AddRange(variacoes);
            context.SaveChanges();
        }
        var variacoesDb = context.Variacoes.ToList();

        // 5. Seed Empreendimentos (Bogus)
        if (!context.Empreendimentos.Any())
        {
            var faker = new Faker("pt_BR");
            
            var prefixosNomes = new[] { "Residencial", "EdifÃ­cio", "CondomÃ­nio", "Parque", "Vila", "Torre", "Complexo", "Plaza", "Jardim", "Spazio", "Ville", "Maison" };
            var sufixosNomes = new[] { "Borges", "Di Roma", "Bravie", "Garden", "Lagos", "das Flores", "do Sol", "Imperial", "Real", "Prime", "Premium", "Unique", "Vision", "Horizon", "Acqua", "Natura", "Bela Vista", "Oasis", "Paradiso", "Exclusive", "Central", "Lumina" };
            
            var tipos = new[] { "Vertical", "Horizontal", "Loteamento" };
            var statusOpcoes = new[] { "LanÃ§amento", "Na Planta", "Em Obras", "Pronto", "Entregue" };
            
            var empreendimentosGerados = new List<Empreendimento>();

            for (int i = 0; i < 350; i++)
            {
                var tipoSelecionado = faker.PickRandom(tipos);
                
                decimal valorBase = 0;
                decimal valorMax = 0;
                
                if (tipoSelecionado == "Loteamento") {
                    valorBase = faker.Random.Number(100000, 300000);
                    valorMax = faker.Random.Number((int)valorBase + 50000, (int)valorBase + 200000);
                } else if (tipoSelecionado == "Horizontal") {
                    valorBase = faker.Random.Number(500000, 2000000);
                    valorMax = faker.Random.Number((int)valorBase + 200000, (int)valorBase + 1500000);
                } else {
                    valorBase = faker.Random.Number(300000, 1500000);
                    valorMax = faker.Random.Number((int)valorBase + 100000, (int)valorBase + 2000000);
                }

                string prevEntrega = faker.PickRandom(statusOpcoes);
                if (prevEntrega != "Entregue" && prevEntrega != "Pronto")
                {
                    prevEntrega = faker.Date.Future(3).ToString("MM/yyyy");
                }

                var emp = new Empreendimento
                {
                    ConstrutoraId = faker.PickRandom(construtorasDb).Id,
                    Nome = $"{faker.PickRandom(prefixosNomes)} {faker.PickRandom(sufixosNomes)} {faker.Name.LastName()}",
                    Descricao = faker.Lorem.Paragraphs(2),
                    Tipo = tipoSelecionado,
                    ValorInicial = valorBase,
                    ValorFinal = valorMax,
                    PrevisaoEntrega = prevEntrega,
                    QtdeTorre = tipoSelecionado == "Vertical" ? faker.Random.Number(1, 5) : 0,
                    QtdeQuadra = tipoSelecionado != "Vertical" ? faker.Random.Number(2, 20) : 0,
                    Status = faker.PickRandom(new[] { "Liberado", "Em AnÃ¡lise", "Bloqueado", "Liberado", "Liberado" }), // Mais chance de liberado
                    GerouUnidades = faker.Random.Bool()
                };
                empreendimentosGerados.Add(emp);
            }

            context.Empreendimentos.AddRange(empreendimentosGerados);
            context.SaveChanges();
        }
        
        var empreendimentosDb = context.Empreendimentos.ToList();

        // Ensure all Empreendimentos have SubtipoId and VariacaoId assigned
        var unassignedEmps = context.Empreendimentos.Where(e => e.SubtipoId == null || e.VariacaoId == null).ToList();
        if (unassignedEmps.Any())
        {
            var rand = new Random();
            foreach (var emp in unassignedEmps)
            {
                if (emp.Tipo == "Horizontal" || emp.Tipo == "Loteamento")
                {
                    emp.SubtipoId = rand.Next(0, 2) == 0 ? 3 : 4; // Condomínio Fechado (3) or Residencial (4)
                    emp.VariacaoId = emp.SubtipoId == 3 ? rand.Next(6, 8) : rand.Next(8, 11); // Lote (6), Casa (7) or Casa Térrea (8), Sobrado (9), Lote (10)
                }
                else
                {
                    emp.SubtipoId = 1; // Apartamento
                    emp.VariacaoId = rand.Next(1, 4); // Studio (1), Loft (2), Padrão (3)
                }
            }
            context.SaveChanges();
        }

        // Ensure all Empreendimentos have a valid Endereco assigned
        var unassignedAddressEmps = context.Empreendimentos.Where(e => e.EnderecoId == null).ToList();
        if (unassignedAddressEmps.Any())
        {
            var firstBairro = context.Bairros.FirstOrDefault();
            var firstCidade = context.Cidades.FirstOrDefault();
            var firstEstado = context.Estados.FirstOrDefault();
            
            if (firstBairro != null && firstCidade != null && firstEstado != null)
            {
                var rand = new Random();
                var logradouros = new[] {
                    "Av. Estêvão de Mendonça", "Rua das Orquídeas", "Av. Miguel Sutil",
                    "Av. Historiador Rubens de Mendonça", "Rua das Flores", "Av. Fernando Corrêa da Costa",
                    "Rua 24 de Outubro", "Av. Getúlio Vargas", "Rua Cândido Mariano"
                };

                foreach (var emp in unassignedAddressEmps)
                {
                    var end = new Endereco
                    {
                        EstadoId = firstEstado.Id,
                        CidadeId = firstCidade.Id,
                        BairroId = firstBairro.Id,
                        Logradouro = logradouros[rand.Next(logradouros.Length)],
                        Numero = (rand.Next(10, 99) * 10).ToString(),
                        Cep = "78000-000",
                        Latitude = emp.Latitude ?? -15.5989m,
                        Longitude = emp.Longitude ?? -56.0949m
                    };
                    context.Enderecos.Add(end);
                    context.SaveChanges();

                    emp.EnderecoId = end.Id;
                }
                context.SaveChanges();
            }
        }

        // 6. Seed Unidades
        if (!context.Unidades.Any())
        {
            var faker = new Faker("pt_BR");
            var unidades = new List<Unidade>();
            
            // Gerar unidades para uma parte dos empreendimentos
            foreach (var emp in empreendimentosDb.Take(100))
            {
                if (emp.GerouUnidades)
                {
                    int qtd = faker.Random.Number(3, 10);
                    for (int i = 0; i < qtd; i++)
                    {
                        unidades.Add(new Unidade {
                            ConstrutoraId = emp.ConstrutoraId,
                            EmpreendimentoId = emp.Id,
                            Nome = emp.Tipo == "Vertical" ? $"Apt {faker.Random.Number(1, 25)}0{faker.Random.Number(1, 8)}" : $"Lote {faker.Random.Number(1, 50)} Qd {faker.Random.Number(1, 10)}",
                            Situacao = faker.PickRandom(new[] { "DisponÃ­vel", "DisponÃ­vel", "Vendida", "Reservada", "Bloqueada" })
                        });
                    }
                }
            }
            context.Unidades.AddRange(unidades);
            context.SaveChanges();
        }

        // 7. Seed Users
        if (!context.Users.Any())
        {
            var plaenge = construtorasDb.FirstOrDefault(c => c.NomeAbreviado == "Plaenge") ?? construtorasDb.First();
            var adminUser = new User
            {
                Name = "Administrador",
                Email = "admin@lancamentos.online",
                PasswordHash = "admin123",
                Celular = "(65) 99999-1111",
                ConstrutoraId = plaenge.Id
            };
            context.Users.Add(adminUser);
            context.SaveChanges();
        }

        // 8. Seed Leads
        if (!context.Leads.Any())
        {
            var faker = new Faker("pt_BR");
            var leads = new List<Lead>();
            
            foreach (var emp in empreendimentosDb.Take(50))
            {
                int qtd = faker.Random.Number(1, 8);
                for (int i = 0; i < qtd; i++)
                {
                    leads.Add(new Lead {
                        ConstrutoraId = emp.ConstrutoraId,
                        EmpreendimentoId = emp.Id,
                        Nome = faker.Name.FullName(),
                        Email = faker.Internet.Email(),
                        Telefone = faker.Phone.PhoneNumber("(##) 9####-####"),
                        Status = faker.PickRandom(new[] { "Novo", "Em Atendimento", "Agendou Visita", "Proposta em AnÃ¡lise", "Venda Fechada", "Perdido" })
                    });
                }
            }
            context.Leads.AddRange(leads);
            context.SaveChanges();
        }
    }

    private static void SeedConstrutorasFromDump(ApplicationDbContext context)
    {
        var dumpPath = @"C:\Projects\novuu\api\construtoras_dump.txt";
        if (!System.IO.File.Exists(dumpPath)) return;

        var lines = System.IO.File.ReadAllLines(dumpPath);
        if (lines.Length <= 1) return;

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;

            var cols = line.Split('\t');
            if (cols.Length < 2) continue;

            if (!int.TryParse(cols[0], out int id)) continue;

            var construtora = context.Construtoras.FirstOrDefault(c => c.Id == id);
            bool isNew = false;
            if (construtora == null)
            {
                construtora = new Construtora { Id = id };
                isNew = true;
            }

            construtora.Nome = cols.Length > 1 && cols[1] != "NULL" ? cols[1] : string.Empty;
            construtora.NomeAbreviado = cols.Length > 2 && cols[2] != "NULL" ? cols[2] : null;
            construtora.RazaoSocial = cols.Length > 3 && cols[3] != "NULL" ? cols[3] : null;
            construtora.Cnpj = cols.Length > 4 && cols[4] != "NULL" ? cols[4] : null;
            var rawLogo = cols.Length > 5 && cols[5] != "NULL" ? cols[5] : null;
            if (!string.IsNullOrWhiteSpace(rawLogo) && !rawLogo.StartsWith("http"))
            {
                var cleanLogo = rawLogo.TrimStart('/', '\\').Replace('/', System.IO.Path.DirectorySeparatorChar);
                var diskPath = System.IO.Path.Combine(@"C:\laragon\www\lancamentos\public", cleanLogo);
                if (!System.IO.File.Exists(diskPath))
                {
                    rawLogo = null;
                }
            }
            construtora.Logo = rawLogo;
            construtora.Observacoes = cols.Length > 6 && cols[6] != "NULL" ? cols[6] : null;
            construtora.TempoMercado = cols.Length > 7 && cols[7] != "NULL" ? cols[7] : null;
            if (cols.Length > 8 && int.TryParse(cols[8], out int ano)) construtora.AnoFundacao = ano;
            if (cols.Length > 9 && int.TryParse(cols[9], out int mes)) construtora.MesFundacao = mes;
            construtora.Email = cols.Length > 10 && cols[10] != "NULL" ? cols[10] : null;
            construtora.Telefone = cols.Length > 11 && cols[11] != "NULL" ? cols[11] : null;
            construtora.CelularAtendimento = cols.Length > 12 && cols[12] != "NULL" ? cols[12] : null;
            construtora.Whatsapp = cols.Length > 13 && cols[13] != "NULL" ? cols[13] : null;
            construtora.UrlHotsite = cols.Length > 14 && cols[14] != "NULL" ? cols[14] : null;
            construtora.Facebook = cols.Length > 15 && cols[15] != "NULL" ? cols[15] : null;
            construtora.Instagram = cols.Length > 16 && cols[16] != "NULL" ? cols[16] : null;
            construtora.Twitter = cols.Length > 17 && cols[17] != "NULL" ? cols[17] : null;
            construtora.Youtube = cols.Length > 18 && cols[18] != "NULL" ? cols[18] : null;
            construtora.Status = cols.Length > 19 && cols[19] != "NULL" ? cols[19] : "Liberada";
            construtora.AcessoDomus = cols.Length > 20 && cols[20] == "Sim";

            if (isNew)
            {
                context.Construtoras.Add(construtora);
            }
        }

        context.SaveChanges();

        try
        {
            context.Database.ExecuteSqlRaw("SELECT setval(pg_get_serial_sequence('\"Construtoras\"', 'Id'), coalesce(max(\"Id\"), 1)) FROM \"Construtoras\";");
        }
        catch { }
    }

    private static void SeedEstadosFromDump(ApplicationDbContext context)
    {
        var dumpPath = @"C:\Projects\novuu\api\estados_dump_utf8.txt";
        if (!System.IO.File.Exists(dumpPath)) return;

        var lines = System.IO.File.ReadAllLines(dumpPath);
        if (lines.Length <= 1) return;

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;

            var cols = line.Split('\t');
            if (cols.Length < 3) continue;
            if (!int.TryParse(cols[0], out int id)) continue;

            var estado = context.Estados.FirstOrDefault(e => e.Id == id);
            if (estado == null)
            {
                estado = new Estado { Id = id, Uf = cols[1], Nome = cols[2] };
                context.Estados.Add(estado);
            }
            else
            {
                estado.Uf = cols[1];
                estado.Nome = cols[2];
            }
        }
        context.SaveChanges();
    }

    private static void SeedCidadesFromDump(ApplicationDbContext context)
    {
        var dumpPath = @"C:\Projects\novuu\api\cidades_dump_utf8.txt";
        if (!System.IO.File.Exists(dumpPath)) return;

        var lines = System.IO.File.ReadAllLines(dumpPath);
        if (lines.Length <= 1) return;

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;

            var cols = line.Split('\t');
            if (cols.Length < 3) continue;
            if (!int.TryParse(cols[0], out int id)) continue;
            if (!int.TryParse(cols[1], out int estadoId)) continue;

            var cidade = context.Cidades.FirstOrDefault(c => c.Id == id);
            if (cidade == null)
            {
                cidade = new Cidade { Id = id, EstadoId = estadoId, Nome = cols[2] };
                context.Cidades.Add(cidade);
            }
            else
            {
                cidade.EstadoId = estadoId;
                cidade.Nome = cols[2];
            }
        }
        context.SaveChanges();
    }

    private static void SeedBairrosFromDump(ApplicationDbContext context)
    {
        var dumpPath = @"C:\Projects\novuu\api\bairros_dump_utf8.txt";
        if (!System.IO.File.Exists(dumpPath)) return;

        var lines = System.IO.File.ReadAllLines(dumpPath);
        if (lines.Length <= 1) return;

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;

            var cols = line.Split('\t');
            if (cols.Length < 3) continue;
            if (!int.TryParse(cols[0], out int id)) continue;
            if (!int.TryParse(cols[1], out int cidadeId)) continue;

            var bairro = context.Bairros.FirstOrDefault(b => b.Id == id);
            if (bairro == null)
            {
                bairro = new Bairro { Id = id, CidadeId = cidadeId, Nome = cols[2] };
                context.Bairros.Add(bairro);
            }
            else
            {
                bairro.CidadeId = cidadeId;
                bairro.Nome = cols[2];
            }
        }
        context.SaveChanges();
    }

    private static void SeedEnderecosFromDump(ApplicationDbContext context)
    {
        var dumpPath = @"C:\Projects\novuu\api\enderecos_dump_utf8.txt";
        if (!System.IO.File.Exists(dumpPath)) return;

        var lines = System.IO.File.ReadAllLines(dumpPath);
        if (lines.Length <= 1) return;

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;

            var cols = line.Split('\t');
            if (cols.Length < 4) continue;
            if (!int.TryParse(cols[0], out int id)) continue;
            int.TryParse(cols[1], out int estadoId);
            int.TryParse(cols[2], out int cidadeId);
            int.TryParse(cols[3], out int bairroId);

            var endereco = context.Enderecos.FirstOrDefault(e => e.Id == id);
            if (endereco == null)
            {
                endereco = new Endereco { Id = id };
                context.Enderecos.Add(endereco);
            }

            endereco.EstadoId = estadoId > 0 ? estadoId : 1;
            endereco.CidadeId = cidadeId > 0 ? cidadeId : 1;
            endereco.BairroId = bairroId > 0 ? bairroId : 1;
            endereco.Cep = cols.Length > 4 && cols[4] != "NULL" ? cols[4] : string.Empty;
            endereco.Logradouro = cols.Length > 5 && cols[5] != "NULL" ? cols[5] : string.Empty;
            endereco.Complemento = cols.Length > 6 && cols[6] != "NULL" ? cols[6] : null;
            endereco.Numero = cols.Length > 7 && cols[7] != "NULL" ? cols[7] : null;

            if (cols.Length > 8 && decimal.TryParse(cols[8].Replace(',', '.'), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out decimal lat))
            {
                endereco.Latitude = lat;
            }
            if (cols.Length > 9 && decimal.TryParse(cols[9].Replace(',', '.'), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out decimal lon))
            {
                endereco.Longitude = lon;
            }
        }
        context.SaveChanges();

        try
        {
            context.Database.ExecuteSqlRaw("SELECT setval(pg_get_serial_sequence('\"enderecos\"', 'id'), coalesce(max(\"id\"), 1)) FROM \"enderecos\";");
        }
        catch { }
    }

    private static void SeedEmpreendimentosEnderecosFromDump(ApplicationDbContext context)
    {
        var dumpPath = @"C:\Projects\novuu\api\empreendimentos_enderecos_dump_utf8.txt";
        if (!System.IO.File.Exists(dumpPath)) return;

        var lines = System.IO.File.ReadAllLines(dumpPath);
        if (lines.Length <= 1) return;

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line)) continue;

            var cols = line.Split('\t');
            if (cols.Length < 2) continue;
            if (!int.TryParse(cols[0], out int empId)) continue;
            if (!int.TryParse(cols[1], out int endId)) continue;

            var emp = context.Empreendimentos.FirstOrDefault(e => e.Id == empId);
            if (emp != null)
            {
                emp.EnderecoId = endId;
            }
        }
        context.SaveChanges();
    }
}
