using System;
using Npgsql;

class Program
{
    static void Main()
    {
        string connStr = "Host=localhost;Database=lancamentos;Username=postgres;Password=259864";
        using var conn = new NpgsqlConnection(connStr);
        conn.Open();

        string sql = @"
            ALTER TABLE clientes ADD COLUMN IF NOT EXISTS foto_url text;
            ALTER TABLE clientes ADD COLUMN IF NOT EXISTS google_id text;
            ALTER TABLE clientes ADD COLUMN IF NOT EXISTS senha_hash text;

            CREATE TABLE IF NOT EXISTS favoritos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id integer NOT NULL,
                empreendimento_id integer NOT NULL,
                created_at timestamp with time zone,
                updated_at timestamp with time zone,
                deleted_at timestamp with time zone
            );

            CREATE TABLE IF NOT EXISTS historico_visitas (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id integer NOT NULL,
                empreendimento_id integer NOT NULL,
                data_acesso timestamp with time zone NOT NULL,
                created_at timestamp with time zone,
                updated_at timestamp with time zone,
                deleted_at timestamp with time zone
            );
        ";

        using var cmd = new NpgsqlCommand(sql, conn);
        cmd.ExecuteNonQuery();
        Console.WriteLine("SQL Executed successfully!");
    }
}
